title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- templates
- .gitignore
ext:
- go
enablerun: true
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - go mod tidy
  - go mod vendor
  after:
  - ./simdht service &
  exit:
  - ps -ef|grep 'simdht service'| grep -v grep
  - ps -ef|grep 'simdht service'| grep -v grep | awk '{print $2}' | xargs kill -9
link: https://github.com/midoks/zzz
